#include "my_parser.h"

char *helplist[MAX_CMD_NUM][MAX_CMD_WORD_NUM] = {
	{"1", "exit"},
	{"4", "show", "om", "switchover", "state"},
	{"5", "set", "ntp", "server", "ip", "<ip>"},
	{"3", "set", "ntp", "disable"},
	{"3", "show", "ntp", "configuration"},
	{"5", "set", "system", "time", "\"<y/m/d", "h:m:s>\""},
	{"2", "show", "system"},
	{"4", "show", "slot", "<slot_id>", "info"},
	{"3", "show", "board", "status"},
	{"1", "passwd"},
	{"3", "show", "board", "info"},
	{"4", "show", "user", "<user_id>", "passwd"},
	{"4", "show", "user", "admin", "passwd"},
	{"4", "show", "user", "maintenance", "passwd"},
	{"4", "show", "user", "debug", "passwd"},
	{"6", "set", "user", "admin", "login", "telnet", "enable"},
	{"6", "set", "user", "admin", "login", "telnet", "disable"},
	{"6", "set", "user", "admin", "login", "ftp", "enable"},
	{"6", "set", "user", "admin", "login", "ftp", "disable"},
	{"6", "set", "user", "<user_id>", "login", "console", "enable"},
	{"6", "set", "user", "<user_id>", "login", "console", "disable"},
	{"6", "set", "user", "<user_id>", "login", "telnet", "enable"},
	{"6", "set", "user", "<user_id>", "login", "telnet", "disable"},
	{"6", "set", "user", "<user_id>", "login", "rcp", "enable"},
	{"6", "set", "user", "<user_id>", "login", "rcp", "disable"},
	{"6", "set", "user", "<user_id>", "login", "snmp", "enable"},
	{"6", "set", "user", "<user_id>", "login", "snmp", "disable"},
	{"6", "set", "user", "<user_id>", "login", "ftp", "enable"},
	{"6", "set", "user", "<user_id>", "login", "ftp", "disable"},
	{"6", "set", "user", "<user_id>", "login", "syslog", "enable"},
	{"6", "set", "user", "<user_id>", "login", "syslog", "disable"},
	{"6", "set", "user", "maintenance", "login", "console", "enable"},
	{"6", "set", "user", "maintenance", "login", "console", "disable"},
	{"6", "set", "user", "maintenance", "login", "snmp", "enable"},
	{"6", "set", "user", "maintenance", "login", "snmp", "disable"},
	{"6", "set", "user", "maintenance", "login", "ftp", "enable"},
	{"6", "set", "user", "maintenance", "login", "ftp", "disable"},
	{"6", "set", "user", "maintenance", "login", "syslog", "enable"},
	{"6", "set", "user", "maintenance", "login", "syslog", "disable"},
	{"6", "set", "user", "debug", "login", "console", "enable"},
	{"6", "set", "user", "debug", "login", "console", "disable"},
	{"6", "set", "user", "debug", "login", "telnet", "enable"},
	{"6", "set", "user", "debug", "login", "telnet", "disable"},
	{"6", "set", "user", "debug", "login", "snmp", "enable"},
	{"6", "set", "user", "debug", "login", "snmp", "disable"},
	{"6", "set", "user", "debug", "login", "ftp", "enable"},
	{"6", "set", "user", "debug", "login", "ftp", "disable"},
	{"6", "set", "user", "debug", "login", "tftp", "enable"},
	{"6", "set", "user", "debug", "login", "tftp", "disable"},
	{"6", "set", "user", "debug", "login", "syslog", "enable"},
	{"6", "set", "user", "debug", "login", "syslog", "disable"},
	{"4", "reset", "user", "<user_id>", "passwd"},
	{"4", "reset", "user", "admin", "passwd"},
	{"4", "reset", "user", "maintenance", "passwd"},
	{"4", "reset", "user", "debug", "passwd"},
	{"4", "set", "device", "id", "<device_id>"},
	{"2", "show", "rule"},
	{"3", "show", "user", "access"},
	{"2", "show", "configuration"},
	{"2", "save", "configuration"},
	{"1", "exitshell"},
	{"1", "restart"},
	{"3", "reboot", "slot", "<slot_id>"},
	{"3", "reboot", "slot", "all"},
	{"2", "restore", "configuration"},
	{"5", "set", "client", "connect", "max", "<num>"},
	{"4", "show", "client", "connect", "max"},
	{"7", "set", "interface", "pos", "<interface_list>", "rx", "descramble", "enable"},
	{"7", "set", "interface", "pos", "<interface_list>", "rx", "descramble", "disable"},
	{"7", "set", "interface", "pos", "<interface_list>", "rx", "crc", "crc_32"},
	{"7", "set", "interface", "pos", "<interface_list>", "rx", "crc", "crc_16"},
	{"5", "set", "interface", "<interface_list>", "type", "pos"},
	{"5", "set", "interface", "<interface_list>", "type", "xge_lan"},
	{"5", "set", "interface", "<interface_list>", "type", "xge_wan"},
	{"4", "set", "interface", "type", "pos"},
	{"4", "set", "interface", "type", "xge_lan"},
	{"4", "set", "interface", "type", "xge_wan"},
	{"5", "set", "link", "status", "autodetect", "enable"},
	{"5", "set", "link", "status", "autodetect", "disable"},
	{"4", "show", "interface", "<interface_list>", "status"},
	{"4", "show", "interface", "<interface_list>", "counter"},
	{"4", "show", "interface", "<interface_list>", "info"},
	{"5", "show", "module", "<module_list>", "fpga", "counter"},
	{"5", "show", "module", "<module_list>", "ddr", "counter"},
	{"4", "clear", "interface", "<interface_list>", "counter"},
	{"5", "clear", "module", "<module_list>", "fpga", "counter"},
	{"5", "clear", "module", "<module_list>", "ddr", "counter"},
	{"7", "set", "interface", "<interface_list>", "fw", "flow", "threshold", "<threshold_kbps>"},
	{"6", "show", "interface", "<interface_list>", "fw", "flow", "threshold"},
	{"3", "show", "interface", "status"},
	{"4", "show", "public", "resource", "allocation"},
	{"6", "show", "user", "<user_id>", "resource", "allocation", "verbose"},
	{"4", "add", "rule", "<class_entry>", "drop"},
	{"5", "add", "static", "rule", "<class_entry>", "drop"},
	{"6", "add", "rule", "<class_entry>", "fw", "outgroup", "<outgroup_id>"},
	{"7", "add", "static", "rule", "<class_entry>", "fw", "outgroup", "<outgroup_id>"},
	{"8", "add", "rule", "<class_entry>", "fw", "outgroup", "<outgroup_id>", "ip_pool", "<pool_id>"},
	{"9", "add", "static", "rule", "<class_entry>", "fw", "outgroup", "<outgroup_id>", "ip_pool", "<pool_id>"},
	{"8", "add", "rule", "<class_entry>", "fw", "outgroup", "<outgroup_id>", "vlan_pool", "<pool_id>"},
	{"9", "add", "static", "rule", "<class_entry>", "fw", "outgroup", "<outgroup_id>", "vlan_pool", "<pool_id>"},
	{"3", "delete", "rule", "<class_entry>"},
	{"3", "delete", "rule", "all"},
	{"3", "check", "rule", "<class_entry>"},
	{"5", "set", "float", "userdata", "rule", "apply"},
	{"5", "set", "ip", "search", "mode", "inside"},
	{"5", "set", "ip", "search", "mode", "outside"},
	{"6", "set", "<ud_id>", "mode", "<ud_mode>", "offset", "<offset>"},
	{"4", "alloc", "rule", "entrynum", "apply"},
	{"4", "alloc", "rule", "entrynum", "default"},
	{"7", "alloc", "public", "rule", "type", "<rule_type>", "entrynum", "<entry_num>"},
	{"8", "alloc", "user", "<user_id>", "rule", "type", "<rule_type>", "entrynum", "<entry_num>"},
	{"4", "show", "rule", "nomask", "configuration"},
	{"6", "set", "rule", "nomask", "pattern", "<id>", "disable"},
	{"6", "set", "rule", "nomask", "pattern", "<id>", "<five_tuple>"},
	{"1", "init"},
	{"1", "sync"},
	{"3", "show", "counter", "<int>"},
	{"3", "clear", "counter", "<int>"},
	{"8", "set", "stream", "aging", "time", "udp", "<time_s>", "tcp", "<time_s>"},
	{"4", "set", "user", "<user_id>", "enable"},
	{"4", "set", "user", "maintenance", "enable"},
	{"4", "set", "user", "debug", "enable"},
	{"4", "set", "user", "<user_id>", "disable"},
	{"4", "set", "user", "maintenance", "disable"},
	{"4", "set", "user", "debug", "disable"},
	{"4", "set", "public", "autobind", "enable"},
	{"4", "set", "public", "autobind", "disable"},
	{"4", "set", "user", "autobind", "enable"},
	{"4", "set", "user", "autobind", "disable"},
	{"3", "set", "fillhead", "enable"},
	{"3", "set", "fillhead", "disable"},
	{"3", "set", "fwhead", "enable"},
	{"3", "set", "fwhead", "disable"},
	{"4", "set", "fwhead", "outgroup", "<outgroup_id>"},
	{"6", "set", "public", "autobind", "aging", "time", "<time_s>"},
	{"6", "set", "user", "autobind", "aging", "time", "<time_s>"},
	{"6", "set", "user", "autobind", "max", "num", "<value>"},
	{"4", "set", "packet", "sample", "enable"},
	{"4", "set", "packet", "sample", "disable"},
	{"9", "set", "packet", "sample", "scale", "<scale>", "hash", "update", "time", "<time_s>"},
	{"5", "set", "packet", "sample", "outgroup", "<outgroup_id>"},
	{"3", "set", "netflow", "enable"},
	{"3", "set", "netflow", "disable"},
	{"9", "set", "netflow", "server", "mac", "<mac>", "ip", "<ip>", "port", "<port>"},
	{"5", "set", "netflow", "sample", "scale", "<scale>"},
	{"5", "set", "netflow", "sample", "outgroup", "<outgroup_id>"},
	{"5", "set", "interface", "<interface_list>", "direction", "up"},
	{"5", "set", "interface", "<interface_list>", "direction", "down"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "up", "s"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "up", "d"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "up", "sd"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "up", "sdsd"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "up", "sdsdp"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "down", "s"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "down", "d"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "down", "sd"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "down", "sdsd"},
	{"6", "set", "outgroup", "<outgroup_id>", "hashmode", "down", "sdsdp"},
	{"4", "add", "outgroup", "<outgroup_id>", "<interface_list>"},
	{"4", "delete", "outgroup", "<outgroup_id>", "<interface_list>"},
	{"4", "delete", "outgroup", "<outgroup_id>", "all"},
	{"4", "add", "ip_pool", "<pool_id>", "<ip>"},
	{"4", "delete", "ip_pool", "<pool_id>", "<ip>"},
	{"4", "delete", "ip_pool", "<pool_id>", "all"},
	{"4", "add", "vlan_pool", "<pool_id>", "<vlan>"},
	{"4", "delete", "vlan_pool", "<pool_id>", "<vlan>"},
	{"4", "delete", "vlan_pool", "<pool_id>", "all"},
	{"4", "alloc", "public", "outport", "<interface_list>"},
	{"5", "alloc", "user", "<user_id>", "outport", "<interface_list>"},
	{"3", "clear", "public", "outport"},
	{"4", "clear", "user", "<user_id>", "outport"},
	{"4", "set", "user", "default", "drop"},
	{"8", "set", "user", "default", "fw", "outgroup", "<outgroup_id>", "[<ip_pool>]", "[<vlan_pool>]"},
	{"4", "set", "strip", "head", "enable"},
	{"4", "set", "strip", "head", "disable"},
	{"2", "lock", "<five_tuple_class_entry>"},
	{"2", "unlock", "<five_tuple_class_entry>"},
	{"6", "set", "stream", "default", "fw", "num", "<num>"},
	{"3", "set", "stream", "enable"},
	{"3", "set", "stream", "disable"},
	{"4", "set", "lock", "outgroup", "<outgroup_id>"},
	{"4", "show", "<five_tuple_class_entry>", "lock", "status"},
	{"4", "set", "unknown", "packet", "drop"},
	{"6", "set", "unknown", "packet", "fw", "outgroup", "<outgroup_id>"},
	{"3", "show", "stream", "counter"},
	{"3", "clear", "stream", "counter"},
	{"3", "set", "failover", "enable"},
	{"3", "set", "failover", "disable"},
	{"6", "set", "failover", "status", "update", "time", "<time_s>"},
	{"4", "show", "se", "build", "time"},
	{"4", "set", "debug", "level", "<debug_level>"},
	{"2", "wget", "<url>"},
	{"3", "enable", "version", "om"},
	{"3", "enable", "version", "<slot_id>"},
	{"3", "disable", "version", "om"},
	{"3", "disable", "version", "<slot_id>"},
	{"4", "enable", "version", "om", "\"<version_name>\""},
	{"4", "enable", "version", "<slot_id>", "\"<version_name>\""},
	{"4", "disable", "version", "om", "\"<version_name>\""},
	{"4", "disable", "version", "<slot_id>", "\"<version_name>\""},
	{"6", "enable", "version", "<slot_id>", "'-'", "<slot_id>", "\"<version_name>\""},
	{"6", "disable", "version", "<slot_id>", "'-'", "<slot_id>", "\"<version_name>\""},
	{"3", "remove", "version", "\"<version_name>\""},
	{"3", "list", "version", "om"},
	{"3", "list", "version", "<slot_id>"},
	{"3", "list", "version", "\"<version_name>\""},
	{"2", "help", "system"},
	{"6", "show", "log", "user", "admin", "priority", "emergency"},
	{"6", "show", "log", "user", "admin", "priority", "alert"},
	{"6", "show", "log", "user", "admin", "priority", "crit"},
	{"6", "show", "log", "user", "admin", "priority", "error"},
	{"6", "show", "log", "user", "admin", "priority", "warn"},
	{"6", "show", "log", "user", "admin", "priority", "notice"},
	{"6", "show", "log", "user", "admin", "priority", "info"},
	{"6", "show", "log", "user", "admin", "priority", "debug"},
	{"6", "show", "log", "user", "debug", "priority", "emergency"},
	{"6", "show", "log", "user", "debug", "priority", "alert"},
	{"6", "show", "log", "user", "debug", "priority", "crit"},
	{"6", "show", "log", "user", "debug", "priority", "error"},
	{"6", "show", "log", "user", "debug", "priority", "warn"},
	{"6", "show", "log", "user", "debug", "priority", "notice"},
	{"6", "show", "log", "user", "debug", "priority", "info"},
	{"6", "show", "log", "user", "debug", "priority", "debug"},
	{"6", "show", "log", "user", "maintenance", "priority", "emergency"},
	{"6", "show", "log", "user", "maintenance", "priority", "alert"},
	{"6", "show", "log", "user", "maintenance", "priority", "crit"},
	{"6", "show", "log", "user", "maintenance", "priority", "error"},
	{"6", "show", "log", "user", "maintenance", "priority", "warn"},
	{"6", "show", "log", "user", "maintenance", "priority", "notice"},
	{"6", "show", "log", "user", "maintenance", "priority", "info"},
	{"6", "show", "log", "user", "maintenance", "priority", "debug"},
	{"6", "show", "log", "user", "<user_id>", "priority", "emergency"},
	{"6", "show", "log", "user", "<user_id>", "priority", "alert"},
	{"6", "show", "log", "user", "<user_id>", "priority", "crit"},
	{"6", "show", "log", "user", "<user_id>", "priority", "error"},
	{"6", "show", "log", "user", "<user_id>", "priority", "warn"},
	{"6", "show", "log", "user", "<user_id>", "priority", "notice"},
	{"6", "show", "log", "user", "<user_id>", "priority", "info"},
	{"6", "show", "log", "user", "<user_id>", "priority", "debug"},
	{"5", "show", "log", "system", "priority", "emergency"},
	{"5", "show", "log", "system", "priority", "alert"},
	{"5", "show", "log", "system", "priority", "crit"},
	{"5", "show", "log", "system", "priority", "error"},
	{"5", "show", "log", "system", "priority", "warn"},
	{"5", "show", "log", "system", "priority", "notice"},
	{"5", "show", "log", "system", "priority", "info"},
	{"5", "show", "log", "system", "priority", "debug"},
	{"4", "show", "log", "priority", "emergency"},
	{"4", "show", "log", "priority", "alert"},
	{"4", "show", "log", "priority", "crit"},
	{"4", "show", "log", "priority", "error"},
	{"4", "show", "log", "priority", "warn"},
	{"4", "show", "log", "priority", "notice"},
	{"4", "show", "log", "priority", "info"},
	{"4", "show", "log", "priority", "debug"},
	{"4", "set", "trap", "log", "enable"},
	{"4", "set", "trap", "log", "disable"},
	{"5", "set", "log", "user", "admin", "enable"},
	{"5", "set", "log", "user", "admin", "disable"},
	{"5", "set", "log", "user", "debug", "enable"},
	{"5", "set", "log", "user", "debug", "disable"},
	{"5", "set", "log", "user", "maintenance", "enable"},
	{"5", "set", "log", "user", "maintenance", "alert"},
	{"5", "set", "log", "user", "<user_id>", "enable"},
	{"5", "set", "log", "user", "<user_id>", "disable"},
	{"4", "set", "log", "system", "enable"},
	{"4", "set", "log", "system", "disable"},
	{"4", "set", "log", "timeformat", "none"},
	{"5", "set", "log", "timeformat", "rfc", "time"},
	{"7", "set", "log", "timeformat", "rfc", "time", "and", "year"},
	{"7", "set", "log", "timeformat", "rfc", "time", "and", "ms"},
	{"8", "set", "log", "timeformat", "rfc", "time", "year", "and", "ms"},
	{"5", "set", "log", "timeformat", "general", "year"},
	{"7", "set", "log", "timeformat", "general", "year", "and", "ms"},
	{"5", "set", "log", "mibinfo", "type", "public"},
	{"5", "set", "log", "mibinfo", "type", "private"},
	{"5", "set", "log", "user", "filesize", "<size_k>"},
	{"5", "set", "log", "system", "filesize", "<size_k>"},
	{"8", "export", "log", "system", "ftp", "<_ipaddr_>", "\"<account_name>\"", "\"<passwd>\"", "\"[path]\""},
	{"9", "export", "log", "user", "admin", "ftp", "<_ipaddr_>", "\"<account_name>\"", "\"<passwd>\"", "\"[path]\""},
	{"9", "export", "log", "user", "debug", "ftp", "<_ipaddr_>", "\"<account_name>\"", "\"<passwd>\"", "\"[path]\""},
	{"9", "export", "log", "user", "maintenance", "ftp", "<_ipaddr_>", "\"<account_name>\"", "\"<passwd>\"", "\"[path]\""},
	{"9", "export", "log", "user", "<user_id>", "ftp", "<_ipaddr_>", "\"<account_name>\"", "\"<passwd>\"", "\"[path]\""},
	{"6", "export", "log", "system", "syslog", "<ipaddr>", "[port_id]"},
	{"7", "export", "log", "user", "admin", "syslog", "<ipaddr>", "[port_id]"},
	{"7", "export", "log", "user", "debug", "syslog", "<ipaddr>", "[port_id]"},
	{"7", "export", "log", "user", "maintenance", "syslog", "<ipaddr>", "[port_id]"},
	{"7", "export", "log", "user", "<user_id>", "syslog", "<ipaddr>", "[port_id]"},
	{"3", "show", "log", "configuration"},
	{"2", "arp", "show"},
	{"4", "arp", "add", "<ip>", "<mac>"},
	{"3", "arp", "delete", "<ip>"},
	{"4", "ifconfig", "<ip>", "netmask", "<mask>"},
	{"2", "route", "show"},
	{"8", "route", "add", "net", "<ip>", "netmask", "<ip>", "gw", "<ip>"},
	{"8", "route", "delete", "net", "<ip>", "netmask", "<ip>", "gw", "<ip>"},
	{"6", "route", "add", "host", "<ip>", "gw", "<ip>"},
	{"6", "route", "delete", "host", "<ip>", "gw", "<ip>"},
	{"2", "snmp", "start"},
	{"2", "snmp", "restart"},
	{"2", "snmp", "stop"},
	{"3", "snmp", "restore", "configuration"},
	{"2", "snmp", "status"},
	{"3", "snmp", "show", "configuration"},
	{"4", "snmp", "set", "sysname", "\"<value>\""},
	{"4", "snmp", "set", "syscontact", "\"<value>\""},
	{"4", "snmp", "set", "syslocation", "\"<value>\""},
	{"5", "snmp", "set", "trap", "version", "\"<value>\""},
	{"4", "snmp", "set", "username", "\"<value>\""},
	{"5", "snmp", "set", "auth", "type", "md5"},
	{"5", "snmp", "set", "auth", "type", "sha"},
	{"5", "snmp", "set", "auth", "password", "\"<value>\""},
	{"5", "snmp", "set", "priv", "type", "des"},
	{"5", "snmp", "set", "priv", "type", "aes"},
	{"5", "snmp", "set", "priv", "password", "\"<value>\""},
	{"4", "snmp", "set", "access", "noauth"},
	{"4", "snmp", "set", "access", "auth"},
	{"4", "snmp", "set", "access", "priv"},
	{"4", "snmp", "add", "rocommunity", "\"<value>\""},
	{"4", "snmp", "delete", "rocommunity", "\"<value>\""},
	{"4", "snmp", "add", "rwcommunity", "\"<value>\""},
	{"4", "snmp", "delete", "rwcommunity", "\"<value>\""},
	{"5", "snmp", "set", "trap", "ip", "<ipaddr>"},
	{"5", "show", "<class_entry>", "outgroup", "<outgroup_id>", "outport"},
	{"4", "set", "interface", "<interface_list>", "shutdown"},
	{"4", "set", "interface", "<interface_list>", "no_shut"},
	{"6", "set", "interface", "<interface_list>", "single_fiber", "transmit", "enable"},
	{"6", "set", "interface", "<interface_list>", "single_fiber", "transmit", "disable"},
	{"2", "show", "tok"},
	{"3", "show", "tok", "<tid>"},
	{"4", "show", "tok", "<tid>", "enable"},
	{"4", "show", "tok", "<tid>", "disable"},
	{"6", "show", "tok", "user", "admin", "priority", "warn"},
	{"6", "show", "tok", "user", "debug", "priority", "warn"},
	{"6", "show", "tok", "user", "admin", "priority", "error"},
	{"5", "show", "tok", "user", "<user_id>", "enable"},
	{"5", "show", "tok", "user", "<user_id>", "disable"},
	{"5", "show", "tok", "user", "admin", "enable"},
	{"5", "show", "tok", "user", "admin", "disable"},
};

char *tokenlist[MAX_CMD_WORD_NUM][MAX_CMD_NUM] = {
	{"0"},
	{"30","exit", "show", "set", "passwd", "reset", "save"
		,"exitshell", "restart", "reboot", "restore", "clear", "add"
		,"delete", "check", "alloc", "init", "sync", "lock"
		,"unlock", "wget", "enable", "disable", "remove", "list"
		,"help", "export", "arp", "ifconfig", "route", "snmp"},
	{"43","om", "ntp", "system", "slot", "board", "user"
		,"device", "rule", "configuration", "client", "interface", "link"
		,"module", "public", "static", "float", "ip", "counter"
		,"stream", "fillhead", "fwhead", "packet", "netflow", "outgroup"
		,"strip", "lock", "unknown", "failover", "se", "debug"
		,"version", "log", "trap", "show", "add", "delete"
		,"start", "restart", "stop", "restore", "status", "set"
		,"tok"},
	{"55","switchover", "server", "disable", "configuration", "time", "status"
		,"info", "admin", "maintenance", "debug", "id", "access"
		,"all", "connect", "pos", "type", "resource", "rule"
		,"userdata", "search", "mode", "entrynum", "nomask", "aging"
		,"autobind", "enable", "outgroup", "sample", "outport", "default"
		,"head", "lock", "packet", "counter", "build", "level"
		,"om", "user", "system", "priority", "log", "timeformat"
		,"mibinfo", "netmask", "net", "host", "sysname", "syscontact"
		,"syslocation", "trap", "username", "auth", "priv", "rocommunity"
		,"rwcommunity"},
	{"57","state", "ip", "info", "passwd", "login", "max"
		,"type", "pos", "autodetect", "status", "counter", "fpga"
		,"ddr", "fw", "allocation", "resource", "drop", "rule"
		,"mode", "apply", "default", "configuration", "pattern", "time"
		,"enable", "disable", "aging", "scale", "outgroup", "mac"
		,"direction", "hashmode", "all", "outport", "update", "admin"
		,"debug", "maintenance", "priority", "emergency", "alert", "crit"
		,"error", "warn", "notice", "none", "rfc", "general"
		,"filesize", "ftp", "syslog", "version", "password", "noauth"
		,"auth", "priv", "shutdown"},
	{"47","telnet", "ftp", "console", "rcp", "snmp", "syslog"
		,"tftp", "rx", "pos", "enable", "disable", "counter"
		,"flow", "allocation", "drop", "outgroup", "fw", "apply"
		,"inside", "outside", "offset", "type", "udp", "time"
		,"num", "up", "down", "priority", "emergency", "alert"
		,"crit", "error", "warn", "notice", "info", "debug"
		,"year", "public", "private", "netmask", "gw", "md5"
		,"sha", "des", "aes", "outport", "transmit"},
	{"25","enable", "disable", "descramble", "crc", "threshold", "verbose"
		,"outgroup", "entrynum", "hash", "ip", "s", "d"
		,"sd", "sdsd", "sdsdp", "emergency", "alert", "crit"
		,"error", "warn", "notice", "info", "debug", "and"
		,"year"},
	{"9","enable", "disable", "entrynum", "tcp", "update", "year"
		,"ms", "and", "gw"},
	{"3","time", "port", "ms"},
	{"0"},
};
